language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - npm install karma karma-coverage
  - gem install rake
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: rake test